spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
ciap.api.base-url=${CIAP_API_BASE_URL:http://localhost:8080}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ciap}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1103}
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.snet.transcriptprocessing=DEBUG
logging.level.com.snet.transcriptprocessing.ari=DEBUG

app.events.source=ari
app.ari.enabled=true
#app.events.source=pbxware
#app.ari.enabled=false
app.ari.host=tst-pbx-01.snetcom.net
app.ari.port=443
app.ari.ssl=true
app.ari.username=at
app.ari.password=NFR_PXz9xw3Z1ak
app.ari.app-name=Sayuru-ubuntu
app.ari.subscribe-all=true
app.ari.debug-topic-enabled=true
app.ari.debug-topic=ari.events