spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:qa-kafka.snet.internal:9092}

ciap.api.base-url=${CIAP_API_BASE_URL:http://qa-ciap.snet.internal:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://qa-postgres.snet.internal:5432/kafka_qa}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:qa_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.snet.transcriptprocessing=INFO
